### ISSUE TITLE
About セクション

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/sample-developer-portfolio#21]
section__title

```html
<section id="about" class="about">
  <h2 class="about__title" data-number="1">About Me</h2>
</section>
```

```css
.about {
      width: min(100%, 1024px);
      margin-inline: auto;
      padding: 100px 0;
}
.about__title {
      display: flex;
      align-items: center;
      gap: 10px;
      color: var(--color-section-headtext);
      font-size: clamp(24px, 5vw, 32px);
      margin-bottom: 40px;
}
.about__title::before {
      content: "0" attr(data-number) ".";
      color: var(--color-primary);
      font-size: clamp(16px, 3vw, 20px);
      font-weight: 400;
}
.about__title::after {
      content: "";
      /* width: 100%; */
      height: 1px;
      background-color: var(--color-section-line);
}
```
