### ISSUE TITLE
setup scss files

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/sample-developer-portfolio#3]
### _mediaquery.scss

```scss
$breakpoints: (
  'sm': 'screen and (width <= 520px)', // 520px以下（520pxも含む）
  'md': 'screen and (width <= 768px)', // 768px以下（768pxも含む）
) !default;

@mixin mq($breakpoint) {
  @media #{map-get($breakpoints, $breakpoint)} {
    @content;
  }
}
```

### _functions.scss

```scss
// example - rem(24) => 1.5rem
@function rem($fontSize) {
  @return calc($fontSize / 16) * 1rem;
}

// hover wrapper
@mixin hover {
  @media (hover: hover) and (pointer: fine) {
    @content;
  }
}
```

### _global.scss

```scss
// line height
$lh_sm: 1.4 !default;
$lh_md: 1.5 !default;
$lh_lg: 1.6 !default;
$lh_xl: 1.7 !default;
$lh_2xl: 1.8 !default;

// font size
// letter spacing
```
