### ISSUE TITLE
Skills セクション

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/sample-developer-portfolio#31]
html

```html
      <!-- prettier-ignore -->
      <section id="skills" class="skills">
        <h2 class="section__title" data-number="2">My Skills</h2>
        <div class="skills__container">
          <div class="skills__item">
            <p class="skills__item__title">HTML</p>
            <progress value="0" max="100" data-value="70" class="progress-bar" ></progress>
          </div>
          <div class="skills__item">
            <p class="skills__item__title">CSS（Scss）</p>
            <progress value="0" max="100" data-value="70" class="progress-bar" ></progress>
          </div>
          <div class="skills__item">
            <p class="skills__item__title">JavaScript（ES6+）</p>
            <progress value="0" max="100" data-value="40" class="progress-bar" ></progress>
          </div>
          <div class="skills__item">
            <p class="skills__item__title">TypeScript</p>
            <progress value="0" max="100" data-value="30" class="progress-bar" ></progress>
          </div>
        </div>
      </section>
```

css

```css
    .skills {
      width: min(100%, 1024px);
      margin-inline: auto;
      padding: 100px 0;
    }
    .skills__container {
      display: flex;
      flex-wrap: wrap;
      align-items: flex-end;
      gap: 40px;
    }
    .skills__item {
      width: 48%;
    }
    .skills__item__title {
      color: var(--color-basetext);
      margin-bottom: 8px;
    }

    /* プログレスバーのスタイル */
    progress {
      width: 100%;
      height: 20px;
      appearance: none;
      border-radius: 999px;
    }
    progress::-webkit-progress-bar {
      background-color: var(--color-section-headtext);
      border-radius: 999px;
    }
    progress::-webkit-progress-value {
      background-color: var(--color-primary);
      border-radius: 999px;
    }
```

GSAP

```js
      gsap.registerPlugin(ScrollTrigger);
      const progressbars = document.querySelectorAll(".progress-bar");
      progressbars.forEach((bar) => {
        const dataValue = bar.getAttribute("data-value");
        gsap.to(bar, {
          scrollTrigger: {
            trigger: ".skills",
            start: "top center",
          },
          value: dataValue,
          duration: 2,
          ease: "power1.inOut",
        });
      });
```
