### ISSUE TITLE
Works セクション

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/sample-developer-portfolio#36]
html

```html
      <section id="works" class="works">
        <h2 class="section__title" data-number="3">My Works</h2>
        <ul class="works__list">
          <li class="works__item">
            <div class="works__item-container">
              <header class="works__item-header">
                <div class="works__item-header-top">
                  <div class="works__item-header-top-icon--folder">
                    <svg
                      width="40"
                      height="41"
                      viewBox="0 0 40 41"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M15.2833 10.6159L18.6167 13.9493H33.3333V30.6159H6.66668V10.6159H15.2833ZM16.6667 7.28259H6.66668C4.83334 7.28259 3.35001 8.78259 3.35001 10.6159L3.33334 30.6159C3.33334 32.4493 4.83334 33.9493 6.66668 33.9493H33.3333C35.1667 33.9493 36.6667 32.4493 36.6667 30.6159V13.9493C36.6667 12.1159 35.1667 10.6159 33.3333 10.6159H20L16.6667 7.28259Z"
                        fill="#0EA5E9"
                      />
                    </svg>
                  </div>
                  <div class="works__item-header-top-icon--external">
                    <svg
                      width="20"
                      height="21"
                      viewBox="0 0 20 21"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M11.6667 3.11597V4.78263H14.6583L6.46667 12.9743L7.64167 14.1493L15.8333 5.95763V8.9493H17.5V3.11597M15.8333 16.4493H4.16667V4.78263H10V3.11597H4.16667C3.72464 3.11597 3.30072 3.29156 2.98816 3.60412C2.67559 3.91668 2.5 4.34061 2.5 4.78263V16.4493C2.5 16.8913 2.67559 17.3153 2.98816 17.6278C3.30072 17.9404 3.72464 18.116 4.16667 18.116H15.8333C16.2754 18.116 16.6993 17.9404 17.0118 17.6278C17.3244 17.3153 17.5 16.8913 17.5 16.4493V10.616H15.8333V16.4493Z"
                        fill="#8892B0"
                      />
                    </svg>
                  </div>
                </div>
                <h3 class="works__item-header-title">
                  <a href="#" target="_blank" rel="noopener noreferrer">
                    Integrating Algolia Search with WordPress Multisite
                  </a>
                </h3>
                <p class="works__item-header-description">
                  Building a custom multisite compatible WordPress plugin to
                  build global search with Algolia
                </p>
              </header>
              <footer class="works__item-footer">
                <ul class="works__item-footer-tags">
                  <li class="works__item-footer-tags-item">Algolia</li>
                  <li class="works__item-footer-tags-item">WordPress</li>
                  <li class="works__item-footer-tags-item">PHP</li>
                </ul>
              </footer>
            </div>
          </li>
        </ul>
        <div class="works__more-btn-wrapper">
          <button class="works__more-btn">Show More</button>
        </div>
      </section>
```

css

```css
    .works {
      display: flex;
      flex-direction: column;
      gap: 40px;
      width: min(100%, 1024px);
      margin-inline: auto;
      padding: 100px 0;
    }

    .works__list {
      position: relative;
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 32px;
      list-style: none;
    }
    .works__item-container {
      position: relative;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      gap: 40px;
      height: 100%;
      padding: 2rem 1.75rem;
      border-radius: 4px;
      background-color: var(--color-background-workbox);
      transition: var(--transition);
    }
    .works__item-container:hover {
      transform: translateY(-7px);
    }

    .works__item-header-top {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 30px;
    }
    .works__item-header-title {
      font-size: 20px;
      font-weight: 600;
      margin-bottom: 20px;
    }
    .works__item-header-title a {
      position: static;
      text-decoration: none;
      color: var(--color-section-headtext);
    }
    .works__item-container:hover .works__item-header-title a {
      color: var(--color-primary);
    }
    .works__item-header-title a::before {
      content: "";
      display: block;
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
    }
    .works__item-header-description {
      font-size: 16px;
      font-weight: 500;
    }

    .works__item-footer-tags {
      display: flex;
      flex-wrap: wrap;
      gap: 5px 15px;
      list-style: none;
    }
    .works__item-footer-tags-item {
      font-size: 14px;
      font-weight: 600;
    }

    .works__more-btn-wrapper {
      display: flex;
      justify-content: center;
      margin-top: 80px;
    }
    .works__more-btn {
      border: 2px solid var(--color-primary);
      border-radius: 4px;
      padding: 16px 28px;
      font-size: clamp(14px, 5vw, 16px);
      font-weight: 500;
      letter-spacing: 0.08em;
      color: var(--color-primary);
      transition: var(--transition);
    }
    .works__more-btn:hover {
      background-color: var(--color-primary-hover);
    }
```
