### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/sample-developer-portfolio#38]
html

```html
    <footer class="footer">© 2023. kitamuraDev - All rights reserved.</footer>
```

css

```css
    .footer {
      text-align: center;
      font-size: 14px;
      font-weight: 500;
      padding: 80px 10px;
      color: var(--color-section-headtext);
    }
```
