### ISSUE TITLE
【components/Header.astro】z-indexをcomponent内のCSS変数で管理する

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/sample-developer-portfolio#9]
[CSS変数 - Astro](https://docs.astro.build/ja/guides/styling/#css%E5%A4%89%E6%95%B0)

```css
:root {
  --layer-1: 100;
  --layer-2: 200;
  --layer-3: 300;
}

.header {
  z-index: var(--layer-1);
}

.modal {
  z-index: var(--layer-3);
}

.popup {
  z-index: var(--layer-2);
}

```
